### PR TITLE
Feature/travis test

### PR DESCRIPTION
**Pull request by EHadoux**
Hi, here is a pull request to automatize build and tests. Plus some corrections on the README.
This will help you to make changes in the code and the build process and make sure everything is alright without pain.

### CODE REVIEW

**Comment by EHadoux** [comment]
Great, thanks.
For the badge in the readme you still need to activate the repo in Travis though.
You just have to go to https://travis-ci.org and authorize the build on this repo.

**Comment by mehdi-kaytoue** [comment]
Activated (I don't really know how it works though :))
BTW I added a full example, that takes a set of replays as input and output the patterns.

**Comment by mehdi-kaytoue** [comment]
It should be LOTV compliant if you use the LOTV branche of SC2READER instead of the master branch.

**Comment by EHadoux** [comment]
Perfect, thanks, I'll have a look this evening.
As you can see, the badge appeared. It will turn green or red depending on the state at the next commit.

**Pull request merged**
